enum LOGGINGLEVEL {
    DEBUG = 0,
    INFO = 1,
    WARNING = 2,
    ERROR = 3,
    FATAL = 4,
}

enum APPLICATION_TYPES {
    HEADLESS_CLIENT = 0,
    MOBILE_CLIENT = 1,
    NG_CLIENT = 2,
    RUNTIME_CLIENT = 3,
    SMART_CLIENT = 4,
    WEB_CLIENT = 5,
}

export { LOGGINGLEVEL, APPLICATION_TYPES };
